name: Crates
version: ${project.version}
author: Dartanman
main: me.dartanman.crates.Crates
commands:
   crate:
     description: Crates base command
     usage: /<command>
     aliases: [crates, dartcrates]