name: Crates
version: 1.0.0
author: Dartanman
main: main.dartanman.crates.Crates
commands:
   crate:
     description: Crates base command
     usage: /<command>
     aliases: [crates, dartcrates]