name: Crates
version: 1.0.1
author: Dartanman
main: me.dartanman.crates.Crates
commands:
   crate:
     description: Crates base command
     usage: /<command>
     aliases: [crates, dartcrates]